backend:
  name: git-gateway
  branch: main

media_folder: "docs/assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "resources"
    label: "Resource Hub"
    folder: "docs/resources"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "html"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Publish Date", widget: "datetime" }
      - { name: "description", label: "Description", widget: "text", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
