backend:
  name: git-gateway
  branch: main

media_folder: "docs/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "articles"
    label: "Resource Hub Articles"
    label_singular: "Article"
    folder: "docs/data"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    identifier_field: "title"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string" }